### ISSUE TITLE
Opening hours / Öffnungszeiten

### ISSUE THREAD

**Issue by creationx** [mhdev/mh_directory#1]
The possibility to define opening hours in every entry.

Öffnungszeiten in einem Eintrag definieren.

**Comment by creationx** [comment]
Added in b1437eb

**Comment by stefan72** [comment]
Hi, thanks for the great extension! A must-have for TYPO3!
I tried the opening hours feature but it dies not seem to work well. In what format would it have to be entered? The end result I wish to have: 
Opening times
Monday - Friday 0800 - 1700
Saturday 0800 - 1200

**Comment by nebrot** [comment]
See last picture: https://github.com/mhdev/mh_directory/wiki/Features#backend-view

This should work:
Mo 08:00-17:00
Di 08:00-17:00
Mi 08:00-17:00
Do 08:00-17:00
Fr 08:00-17:00
Sa 08:00-12:00
So -

**Comment by stefan72** [comment]
Ok, thanks! Did not check the feature page in the wiki. Sorry.

**Comment by creationx** [comment]
No problem stefan72 ... it works now? 
Thanks nebrot for mention that!

**Comment by stefan72** [comment]
works like a charm thanks - keep going.
